version: '3.8'

services:
  mastercard-pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - API_KEY=${API_KEY}
      # Nombre del servicio abajo: localstack
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack

  localstack:
    container_name: localstack_main
    image: localstack/localstack:3.0
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - ACTIVATE_PRO=false
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"