version: '3.8'

services:
  mastercard-pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - API_KEY=${API_KEY}
      # donde vive el AWS falso usando el nombre del servicio
      - AWS_ENDPOINT_URL=http://localstack:4566
    networks:
      - mastercard-network
    command: python main.py

  # El simulador de AWS (LocalStack)
  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    networks:
      - mastercard-network

networks:
  mastercard-network:
    driver: bridge