version: '3.8'

services:
  mastercard-pipeline:
    build: .
    volumes:
      - ./data:/app/data  
      - ./.env:/app/.env  
    environment:
      - API_KEY=${API_KEY}  
    command: python main.py